SP-4997 Fail build-aws if spack.lock changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -107,9 +107,22 @@ build-aws:
     - spack config add "config:install_tree:padded_length:128"
     # Should push to buildcache automatically via --autopush above
     - spack install --use-cache
+    # fail if env/aws/spack.lock was changed
+    - if ! git diff --quiet env/aws/spack.lock; then
+         echo "===============================================================================";
+         echo "The env/aws/spack.lock file changed after 'spack install', which means that it";
+         echo "did not implement spack.lock correctly (either because of new specs or changes";
+         echo "in packages). In either case, check whether the concretisation above makes sense,";
+         echo "and if so commit the spack.lock generated from this CI job:";
+         echo "";
+         echo "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/env/aws/spack.lock";
+         echo "===============================================================================";
+         exit 1;
+      fi
   artifacts:
     paths:
       - env/aws/spack.lock
+    when: always
 
 deploy-aws:
   stage: publish
